x-rabbitmq-client-env: &rabbitmq-client-env
  RABBITMQ_HOST: sd-rabbitmq

services:
  sd-rabbitmq:
    image: rabbitmq:3.13.0-alpine
    container_name: sd-rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_running
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 3s

  sd-rabbitmq-producer: &rabbitmq-client
    build: ./producer
    container_name: sd-rabbitmq-producer
    environment: *rabbitmq-client-env
    depends_on:
      sd-rabbitmq:
        condition: service_healthy

  sd-rabbitmq-consumer1: &sd-rabbitmq-consumer
    <<: *rabbitmq-client
    build: ./consumer
    container_name: sd-rabbitmq-consumer1
    environment:
      <<: *rabbitmq-client-env
      CONSUMER_NAME: "sd-rabbitmq-consumer2"

  sd-rabbitmq-consumer2:
    <<: *sd-rabbitmq-consumer 
    container_name: sd-rabbitmq-consumer2
    environment:
      <<: *rabbitmq-client-env
      CONSUMER_NAME: "sd-rabbitmq-consumer2"
