services:
  sd-rabbitmq:
    image: rabbitmq:3.13.0-alpine
    container_name: sd-rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_running
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 3s

  sd-rabbitmq-rpc-server: &rabbitmq-client
    build: ./server
    image: java-rabbitmq
    container_name: rpc-server
    environment:
      RABBITMQ_HOST: sd-rabbitmq
    depends_on:
      sd-rabbitmq:
        condition: service_healthy

  sd-rabbitmq-rpc-client:
    <<: *rabbitmq-client
    build: ./client
    image: python-rabbitmq
    container_name: rpc-client
    depends_on:
      - sd-rabbitmq-rpc-server
